import '../models/lesson.dart';

class ContentService {
  ContentService._();
  static final ContentService _instance = ContentService._();
  factory ContentService() => _instance;

  // Get lessons for a specific subject
  List<Lesson> getLessonsForSubject(String subjectId) {
    switch (subjectId) {
      case 'math':
        return _createMathLessons();
      case 'science':
        return _createScienceLessons();
      case 'english':
        return _createEnglishLessons();
      case 'history':
        return _createHistoryLessons();
      default:
        return [];
    }
  }

  // ==========================================
  // MATHEMATICS LESSONS (Keep existing)
  // ==========================================
  List<Lesson> _createMathLessons() {
    return [
      _createLesson(
        id: 'math_1',
        title: 'Introduction to Fractions',
        order: 1,
        content: [
          '# Introduction to Fractions',
          '',
          '## What is a Fraction?',
          '',
          'A **fraction** represents a part of a whole.',
          '',
          '### Parts of a Fraction',
          '- **Numerator**: Top number (parts we have)',
          '- **Denominator**: Bottom number (total parts)',
          '',
          '### Example',
          'A pizza cut into 4 slices:',
          '- Eat 1 slice → 1/4 eaten',
          '- 3 slices remain → 3/4 remaining',
          '',
          '## Types of Fractions',
          '',
          '### Proper Fractions',
          'Numerator < Denominator (e.g., 1/2, 2/3, 3/4)',
          '',
          '### Improper Fractions',
          'Numerator ≥ Denominator (e.g., 5/3, 7/4)',
          '',
          '### Mixed Numbers',
          'Whole number + fraction (e.g., 1½, 2¾)',
          '',
          '## Equivalent Fractions',
          '1/2 = 2/4 = 4/8 = 8/16',
          '',
          '**Great job!** Now you understand fractions!',
        ].join('\n'),
        quiz: Quiz(
          id: 'math_q1',
          questions: [
            Question(
              id: 'mq1',
              type: 'mcq',
              text: 'What is the top number called?',
              options: ['Denominator', 'Numerator', 'Whole', 'Divisor'],
              correctAnswer: 'Numerator',
            ),
            Question(
              id: 'mq2',
              type: 'mcq',
              text: 'Which is an improper fraction?',
              options: ['1/2', '3/4', '5/3', '2/5'],
              correctAnswer: '5/3',
            ),
            Question(
              id: 'mq3',
              type: 'true_false',
              text: '1/2 and 2/4 are equivalent.',
              options: ['True', 'False'],
              correctAnswer: 'True',
            ),
          ],
        ),
      ),
      _createLesson(
        id: 'math_2',
        title: 'Adding Fractions',
        order: 2,
        content: [
          '# Adding Fractions',
          '',
          '## Same Denominator',
          'Just add numerators, keep denominator.',
          'Example: 1/5 + 2/5 = 3/5',
          '',
          '## Different Denominators',
          '1. Find LCD',
          '2. Convert fractions',
          '3. Add numerators',
          '4. Simplify',
          '',
          'Example: 1/3 + 1/4',
          'LCD = 12',
          '1/3 = 4/12, 1/4 = 3/12',
          '4/12 + 3/12 = 7/12',
          '',
          '**Practice makes perfect!**',
        ].join('\n'),
        quiz: Quiz(
          id: 'math_q2',
          questions: [
            Question(
              id: 'mq4',
              type: 'mcq',
              text: 'What is 2/7 + 3/7?',
              options: ['5/7', '5/14', '6/7', '1/7'],
              correctAnswer: '5/7',
            ),
            Question(
              id: 'mq5',
              type: 'mcq',
              text: 'LCD of 1/2 and 1/3?',
              options: ['2', '3', '5', '6'],
              correctAnswer: '6',
            ),
          ],
        ),
      ),
      _createLesson(
        id: 'math_3',
        title: 'Fractions in Daily Life',
        order: 3,
        content: [
          '# Fractions in Daily Life',
          '',
          '## Cooking',
          '- ½ cup sugar',
          '- ¼ teaspoon salt',
          '- ¾ cup milk',
          '',
          '## Time',
          '- ½ hour = 30 minutes',
          '- ¼ hour = 15 minutes',
          '',
          '## Shopping',
          '- 50% off = ½ price',
          '- 25% off = ¼ off',
          '',
          'Fractions are everywhere! 🎉',
        ].join('\n'),
        quiz: Quiz(
          id: 'math_q3',
          questions: [
            Question(
              id: 'mq6',
              type: 'mcq',
              text: '½ hour = ? minutes',
              options: ['15', '30', '45', '60'],
              correctAnswer: '30',
            ),
            Question(
              id: 'mq7',
              type: 'true_false',
              text: '50% discount means half price.',
              options: ['True', 'False'],
              correctAnswer: 'True',
            ),
          ],
        ),
      ),
    ];
  }

  // ==========================================
  // SCIENCE LESSONS
  // ==========================================
  List<Lesson> _createScienceLessons() {
    return [
      _createLesson(
        id: 'sci_1',
        title: 'Parts of a Plant',
        order: 1,
        content: [
          '# Parts of a Plant',
          '',
          '## Main Parts',
          '',
          '### 1. Roots 🌱',
          '- Grow underground',
          '- Absorb water and minerals',
          '- Anchor the plant',
          '',
          '### 2. Stem 🌿',
          '- Supports the plant',
          '- Transports water and food',
          '- Holds leaves and flowers',
          '',
          '### 3. Leaves 🍃',
          '- Make food (photosynthesis)',
          '- Breathe (exchange gases)',
          '- Green due to chlorophyll',
          '',
          '### 4. Flowers 🌸',
          '- Reproductive part',
          '- Produce fruits and seeds',
          '- Attract pollinators',
          '',
          '### 5. Fruits 🍎',
          '- Protect seeds',
          '- Help in seed dispersal',
          '',
          '## Fun Fact',
          'The largest flower is Rafflesia - 3 feet wide!',
          '',
          '**Plants are amazing!** 🌿',
        ].join('\n'),
        quiz: Quiz(
          id: 'sci_q1',
          questions: [
            Question(
              id: 'sq1',
              type: 'mcq',
              text: 'Which part makes food?',
              options: ['Roots', 'Stem', 'Leaves', 'Flowers'],
              correctAnswer: 'Leaves',
            ),
            Question(
              id: 'sq2',
              type: 'mcq',
              text: 'Roots absorb?',
              options: ['Sunlight', 'Water', 'Air', 'Food'],
              correctAnswer: 'Water',
            ),
            Question(
              id: 'sq3',
              type: 'true_false',
              text: 'Flowers produce fruits.',
              options: ['True', 'False'],
              correctAnswer: 'True',
            ),
          ],
        ),
      ),
      _createLesson(
        id: 'sci_2',
        title: 'Animals Classification',
        order: 2,
        content: [
          '# Animals Classification',
          '',
          '## Types of Animals',
          '',
          '### 1. Mammals 🐄',
          '- Give birth to babies',
          '- Feed milk to young',
          '- Have hair or fur',
          '- Examples: Cow, Dog, Human',
          '',
          '### 2. Birds 🐦',
          '- Have feathers and wings',
          '- Lay eggs',
          '- Have beaks',
          '- Examples: Eagle, Sparrow, Penguin',
          '',
          '### 3. Reptiles 🦎',
          '- Cold-blooded',
          '- Lay eggs',
          '- Have scales',
          '- Examples: Snake, Lizard, Crocodile',
          '',
          '### 4. Amphibians 🐸',
          '- Live on land and water',
          '- Lay eggs in water',
          '- Examples: Frog, Salamander',
          '',
          '### 5. Fish 🐟',
          '- Live in water',
          '- Have gills to breathe',
          '- Examples: Shark, Goldfish',
          '',
          '**Nature is diverse!** 🌍',
        ].join('\n'),
        quiz: Quiz(
          id: 'sci_q2',
          questions: [
            Question(
              id: 'sq4',
              type: 'mcq',
              text: 'Which animals feed milk?',
              options: ['Birds', 'Mammals', 'Reptiles', 'Fish'],
              correctAnswer: 'Mammals',
            ),
            Question(
              id: 'sq5',
              type: 'true_false',
              text: 'Frogs are amphibians.',
              options: ['True', 'False'],
              correctAnswer: 'True',
            ),
          ],
        ),
      ),
      _createLesson(
        id: 'sci_3',
        title: 'Human Body Systems',
        order: 3,
        content: [
          '# Human Body Systems',
          '',
          '## Major Systems',
          '',
          '### 1. Digestive System 🍔',
          '- Breaks down food',
          '- Absorbs nutrients',
          '- Organs: Stomach, Intestines',
          '',
          '### 2. Respiratory System 🫁',
          '- Helps us breathe',
          '- Takes in oxygen',
          '- Organs: Lungs, Nose',
          '',
          '### 3. Circulatory System ❤️',
          '- Pumps blood',
          '- Transports oxygen',
          '- Organs: Heart, Blood vessels',
          '',
          '### 4. Nervous System 🧠',
          '- Controls body',
          '- Sends signals',
          '- Organs: Brain, Nerves',
          '',
          '## Fun Fact',
          'Your heart beats 100,000 times per day!',
          '',
          '**Your body is incredible!** 💪',
        ].join('\n'),
        quiz: Quiz(
          id: 'sci_q3',
          questions: [
            Question(
              id: 'sq6',
              type: 'mcq',
              text: 'Which organ pumps blood?',
              options: ['Brain', 'Lungs', 'Heart', 'Stomach'],
              correctAnswer: 'Heart',
            ),
            Question(
              id: 'sq7',
              type: 'true_false',
              text: 'Brain is part of nervous system.',
              options: ['True', 'False'],
              correctAnswer: 'True',
            ),
          ],
        ),
      ),
    ];
  }

  // ==========================================
  // ENGLISH LESSONS
  // ==========================================
  List<Lesson> _createEnglishLessons() {
    return [
      _createLesson(
        id: 'eng_1',
        title: 'Nouns - Naming Words',
        order: 1,
        content: [
          '# Nouns - Naming Words',
          '',
          '## What is a Noun?',
          'A noun is a word that names a **person, place, thing, or idea**.',
          '',
          '## Types of Nouns',
          '',
          '### 1. Proper Nouns',
          '- Names specific people/places',
          '- Always start with CAPITAL letter',
          '- Examples: Ravi, Delhi, India, Ganga',
          '',
          '### 2. Common Nouns',
          '- General names',
          '- Examples: boy, city, river, book',
          '',
          '### 3. Collective Nouns',
          '- Names a group',
          '- Examples: team, family, class, herd',
          '',
          '### 4. Abstract Nouns',
          '- Names ideas/feelings',
          '- Examples: love, happiness, courage',
          '',
          '## Practice',
          'Identify nouns: "Ravi went to school."',
          '- Ravi (Proper Noun)',
          '- School (Common Noun)',
          '',
          '**Nouns are everywhere!** 📝',
        ].join('\n'),
        quiz: Quiz(
          id: 'eng_q1',
          questions: [
            Question(
              id: 'eq1',
              type: 'mcq',
              text: '"Delhi" is a?',
              options: ['Common', 'Proper', 'Collective', 'Abstract'],
              correctAnswer: 'Proper',
            ),
            Question(
              id: 'eq2',
              type: 'mcq',
              text: '"Happiness" is a?',
              options: ['Proper', 'Common', 'Collective', 'Abstract'],
              correctAnswer: 'Abstract',
            ),
          ],
        ),
      ),
      _createLesson(
        id: 'eng_2',
        title: 'Verbs - Action Words',
        order: 2,
        content: [
          '# Verbs - Action Words',
          '',
          '## What is a Verb?',
          'A verb shows **action** or **state of being**.',
          '',
          '## Types of Verbs',
          '',
          '### 1. Action Verbs',
          '- Show physical/mental action',
          '- Examples: run, eat, think, write',
          '',
          '### 2. Helping Verbs',
          '- Help main verbs',
          '- Examples: is, am, are, was, were',
          '- "She IS reading"',
          '',
          '### 3. Linking Verbs',
          '- Connect subject to description',
          '- Examples: is, seems, becomes',
          '- "He IS happy"',
          '',
          '## Examples in Sentences',
          '- Ravi **runs** fast.',
          '- Priya **is** a good student.',
          '- They **are** playing.',
          '',
          '**Verbs bring sentences to life!** ⚡',
        ].join('\n'),
        quiz: Quiz(
          id: 'eng_q2',
          questions: [
            Question(
              id: 'eq3',
              type: 'mcq',
              text: 'Which is an action verb?',
              options: ['is', 'am', 'run', 'were'],
              correctAnswer: 'run',
            ),
            Question(
              id: 'eq4',
              type: 'true_false',
              text: '"is" is a helping verb.',
              options: ['True', 'False'],
              correctAnswer: 'True',
            ),
          ],
        ),
      ),
      _createLesson(
        id: 'eng_3',
        title: 'Simple Sentences',
        order: 3,
        content: [
          '# Simple Sentences',
          '',
          '## What is a Sentence?',
          'A sentence is a group of words that makes **complete sense**.',
          '',
          '## Parts of a Sentence',
          '',
          '### Subject',
          '- Who or what the sentence is about',
          '- Example: **Ravi** reads a book.',
          '',
          '### Predicate',
          '- What the subject does',
          '- Example: Ravi **reads a book**.',
          '',
          '## Types of Sentences',
          '',
          '### 1. Declarative (Statement)',
          '- Tells something',
          '- Ends with period (.)',
          '- "The sun rises in the east."',
          '',
          '### 2. Interrogative (Question)',
          '- Asks something',
          '- Ends with question mark (?)',
          '- "What is your name?"',
          '',
          '### 3. Imperative (Command)',
          '- Gives order/request',
          '- "Please sit down."',
          '',
          '### 4. Exclamatory',
          '- Shows strong feeling',
          '- Ends with (!)',
          '- "What a beautiful day!"',
          '',
          '**Practice writing sentences!** ✍️',
        ].join('\n'),
        quiz: Quiz(
          id: 'eng_q3',
          questions: [
            Question(
              id: 'eq5',
              type: 'mcq',
              text: '"What is your name?" is?',
              options: [
                'Declarative',
                'Interrogative',
                'Imperative',
                'Exclamatory',
              ],
              correctAnswer: 'Interrogative',
            ),
            Question(
              id: 'eq6',
              type: 'true_false',
              text: 'A sentence must have subject and predicate.',
              options: ['True', 'False'],
              correctAnswer: 'True',
            ),
          ],
        ),
      ),
    ];
  }

  // ==========================================
  // HISTORY LESSONS
  // ==========================================
  List<Lesson> _createHistoryLessons() {
    return [
      _createLesson(
        id: 'his_1',
        title: 'Ancient India - Indus Valley',
        order: 1,
        content: [
          '# Ancient India - Indus Valley',
          '',
          '## Indus Valley Civilization (3300-1300 BCE)',
          '',
          'One of the **oldest civilizations** in the world!',
          '',
          '## Major Cities',
          '',
          '### 1. Harappa (Punjab, Pakistan)',
          '- Discovered in 1921',
          '- Well-planned streets',
          '- Great Granary',
          '',
          '### 2. Mohenjo-Daro (Sindh, Pakistan)',
          '- Discovered in 1922',
          '- Great Bath',
          '- Advanced drainage system',
          '',
          '## Achievements',
          '- 🏙️ Town planning with grid system',
          '- 💧 Underground drainage',
          '- 📝 Indus script (still undeciphered)',
          '- ⚖️ Standard weights and measures',
          '- 🌾 Agriculture: wheat, barley, cotton',
          '',
          '## Daily Life',
          '- People were farmers and traders',
          '- Used bronze tools',
          '- Made pottery and jewelry',
          '- Traded with Mesopotamia',
          '',
          '**Our ancestors were brilliant!** 🏛️',
        ].join('\n'),
        quiz: Quiz(
          id: 'his_q1',
          questions: [
            Question(
              id: 'hq1',
              type: 'mcq',
              text: 'Great Bath was in?',
              options: ['Harappa', 'Mohenjo-Daro', 'Delhi', 'Agra'],
              correctAnswer: 'Mohenjo-Daro',
            ),
            Question(
              id: 'hq2',
              type: 'true_false',
              text: 'Indus Valley had drainage system.',
              options: ['True', 'False'],
              correctAnswer: 'True',
            ),
          ],
        ),
      ),
      _createLesson(
        id: 'his_2',
        title: 'Freedom Struggle',
        order: 2,
        content: [
          '# Indian Freedom Struggle',
          '',
          '## Key Events',
          '',
          '### 1857 - First War of Independence',
          '- Also called Sepoy Mutiny',
          '- Started in Meerut',
          '- Mangal Pandey played key role',
          '',
          '### 1885 - Indian National Congress',
          '- Founded by A.O. Hume',
          '- First session in Bombay',
          '',
          '### 1919 - Jallianwala Bagh',
          '- Massacre in Amritsar',
          '- General Dyer ordered firing',
          '',
          '### 1930 - Dandi March',
          '- Led by Mahatma Gandhi',
          '- Salt Satyagraha',
          '- 24 days, 390 km march',
          '',
          '### 1942 - Quit India Movement',
          '- "Do or Die" slogan',
          '- Mass protests across India',
          '',
          '### 1947 - Independence',
          '- August 15, 1947',
          '- India becomes free! 🇮🇳',
          '',
          '## Great Leaders',
          '- Mahatma Gandhi',
          '- Jawaharlal Nehru',
          '- Sardar Patel',
          '- Bhagat Singh',
          '',
          '**Jai Hind!** 🇮🇳',
        ].join('\n'),
        quiz: Quiz(
          id: 'his_q2',
          questions: [
            Question(
              id: 'hq3',
              type: 'mcq',
              text: 'Dandi March was in?',
              options: ['1919', '1930', '1942', '1947'],
              correctAnswer: '1930',
            ),
            Question(
              id: 'hq4',
              type: 'true_false',
              text: 'India got freedom in 1947.',
              options: ['True', 'False'],
              correctAnswer: 'True',
            ),
          ],
        ),
      ),
      _createLesson(
        id: 'his_3',
        title: 'Indian Heritage & Culture',
        order: 3,
        content: [
          '# Indian Heritage & Culture',
          '',
          '## Diversity of India',
          '',
          'India is known for **Unity in Diversity**!',
          '',
          '## Festivals',
          '',
          '### National Festivals',
          '- 🇮🇳 Republic Day (Jan 26)',
          '- 🇮🇳 Independence Day (Aug 15)',
          '- 🇮🇳 Gandhi Jayanti (Oct 2)',
          '',
          '### Religious Festivals',
          '- 🪔 Diwali - Festival of Lights',
          '- 🎨 Holi - Festival of Colors',
          '- 🕌 Eid - Islamic festival',
          '- 🎄 Christmas - Christian festival',
          '',
          '## Classical Dances',
          '- Bharatanatyam (Tamil Nadu)',
          '- Kathak (North India)',
          '- Kathakali (Kerala)',
          '- Odissi (Odisha)',
          '',
          '## Monuments',
          '- 🏰 Taj Mahal (Agra)',
          '- 🛕 Qutub Minar (Delhi)',
          '- 🏯 Red Fort (Delhi)',
          '- 🕉️ Konark Temple (Odisha)',
          '',
          '## Food Diversity',
          '- North: Roti, Dal, Paneer',
          '- South: Dosa, Idli, Sambar',
          '- East: Fish curry, Rice',
          '- West: Dhokla, Vada Pav',
          '',
          '**Proud to be Indian!** 🇮🇳',
        ].join('\n'),
        quiz: Quiz(
          id: 'his_q3',
          questions: [
            Question(
              id: 'hq5',
              type: 'mcq',
              text: 'Taj Mahal is in?',
              options: ['Delhi', 'Agra', 'Jaipur', 'Mumbai'],
              correctAnswer: 'Agra',
            ),
            Question(
              id: 'hq6',
              type: 'true_false',
              text: 'Bharatanatyam is from Tamil Nadu.',
              options: ['True', 'False'],
              correctAnswer: 'True',
            ),
          ],
        ),
      ),
    ];
  }

  // Helper to create a lesson
  Lesson _createLesson({
    required String id,
    required String title,
    required String content,
    required int order,
    Quiz? quiz,
  }) {
    return Lesson(
      id: id,
      title: title,
      content: content,
      order: order,
      quiz: quiz,
    );
  }
}
