import '../models/lesson.dart';

class ContentService {
  // Singleton pattern
  ContentService._();
  static final ContentService _instance = ContentService._();
  factory ContentService() => _instance;

  // Cache lessons in memory
  List<Lesson>? _cachedLessons;

  // Get all lessons
  List<Lesson> getLessons() {
    if (_cachedLessons != null) {
      return _cachedLessons!;
    }
    _cachedLessons = _createSampleLessons();
    return _cachedLessons!;
  }

  // Get a specific lesson by ID
  Lesson? getLessonById(String id) {
    try {
      return getLessons().firstWhere((l) => l.id == id);
    } catch (e) {
      return null;
    }
  }

  // Get lessons count
  int getLessonCount() {
    return getLessons().length;
  }

  // Create sample lessons
  List<Lesson> _createSampleLessons() {
    return [_createLesson1(), _createLesson2(), _createLesson3()];
  }

  // ==========================================
  // LESSON 1
  // ==========================================
  Lesson _createLesson1() {
    final content = [
      '# Introduction to Fractions',
      '',
      '## What is a Fraction?',
      '',
      'A **fraction** represents a part of a whole. It shows how many equal parts of a whole are being considered.',
      '',
      '### Parts of a Fraction',
      '',
      '- **Numerator**: The top number (shows how many parts we have)',
      '- **Denominator**: The bottom number (shows total equal parts)',
      '',
      '### Example: Understanding 1/4',
      '',
      'Imagine you have a pizza cut into **4 equal slices**.',
      '',
      '- If you eat **1 slice**, you ate **1/4** (one-fourth) of the pizza',
      '- **3 slices** remain, which is **3/4** (three-fourths) of the pizza',
      '',
      '```',
      '    1     ← Numerator (parts you ate)',
      '  ─────',
      '    4     ← Denominator (total parts)',
      '```',
      '',
      '---',
      '',
      '## Types of Fractions',
      '',
      '### 1. Proper Fractions',
      '',
      'The numerator is **smaller than** the denominator.',
      '',
      '**Examples:**',
      '- 1/2 (one-half)',
      '- 2/3 (two-thirds)',
      '- 3/4 (three-fourths)',
      '',
      '> These fractions are always **less than 1**.',
      '',
      '### 2. Improper Fractions',
      '',
      'The numerator is **larger than or equal to** the denominator.',
      '',
      '**Examples:**',
      '- 5/3 (five-thirds)',
      '- 7/4 (seven-fourths)',
      '- 8/8 (eight-eighths = 1)',
      '',
      '> These fractions are **equal to or greater than 1**.',
      '',
      '### 3. Mixed Numbers',
      '',
      'A combination of a **whole number** and a **proper fraction**.',
      '',
      '**Example:**',
      '- 1½ = one and a half',
      '- 2¾ = two and three-fourths',
      '',
      '---',
      '',
      '## Visualizing Fractions',
      '',
      'Imagine a circle divided into **8 equal parts**:',
      '',
      '| Parts Shaded | Fraction | Simplified |',
      '|-------------|----------|------------|',
      '| 1 part | 1/8 | 1/8 |',
      '| 2 parts | 2/8 | 1/4 |',
      '| 4 parts | 4/8 | 1/2 |',
      '| 8 parts | 8/8 | 1 (whole) |',
      '',
      '---',
      '',
      '## Equivalent Fractions',
      '',
      'Different fractions can represent the **same amount**!',
      '',
      '```',
      '1/2  =  2/4  =  4/8  =  8/16',
      '```',
      '',
      '### How to Find Equivalent Fractions',
      '',
      '**Multiply or divide** both numerator and denominator by the **same number**:',
      '',
      '```',
      '1/2 × 2/2 = 2/4',
      '1/2 × 4/4 = 4/8',
      '```',
      '',
      '---',
      '',
      '## Key Points to Remember',
      '',
      '1. ✅ The denominator **cannot be zero**',
      '2. ✅ Fractions show **parts of a whole**',
      '3. ✅ Equivalent fractions have the **same value**',
      '4. ✅ Every fraction is a **division problem**: 3/4 = 3 ÷ 4',
      '5. ✅ Proper fractions are **less than 1**',
      '6. ✅ Improper fractions are **greater than or equal to 1**',
      '',
      '---',
      '',
      '## Practice Questions',
      '',
      'Try these yourself before taking the quiz:',
      '',
      '1. What fraction of a week is 3 days? (Hint: week = 7 days)',
      '2. If you eat 2 slices of a pizza cut into 6 slices, what fraction did you eat?',
      '3. Are 3/6 and 1/2 equivalent? Why?',
      '',
      '---',
      '',
      '**Great job!** Now you understand the basics of fractions.',
      'Take the quiz to test your knowledge!',
    ].join('\n');

    return Lesson(
      id: 'lesson_1',
      title: 'Introduction to Fractions',
      content: content,
      order: 1,
      quiz: Quiz(
        id: 'quiz_1',
        questions: [
          Question(
            id: 'q1',
            type: 'mcq',
            text: 'What is the top number in a fraction called?',
            options: ['Denominator', 'Numerator', 'Whole number', 'Divisor'],
            correctAnswer: 'Numerator',
            points: 1,
          ),
          Question(
            id: 'q2',
            type: 'mcq',
            text: 'In the fraction 3/4, what does 4 represent?',
            options: [
              'Parts we have',
              'Total equal parts',
              'Parts remaining',
              'The answer',
            ],
            correctAnswer: 'Total equal parts',
            points: 1,
          ),
          Question(
            id: 'q3',
            type: 'true_false',
            text: '1/2 and 2/4 are equivalent fractions.',
            options: ['True', 'False'],
            correctAnswer: 'True',
            points: 1,
          ),
          Question(
            id: 'q4',
            type: 'mcq',
            text: 'Which of these is an improper fraction?',
            options: ['1/2', '3/4', '5/3', '2/5'],
            correctAnswer: '5/3',
            points: 1,
          ),
          Question(
            id: 'q5',
            type: 'mcq',
            text:
                'If you have a pizza cut into 8 slices and you eat 3, what fraction is left?',
            options: ['3/8', '5/8', '8/8', '1/2'],
            correctAnswer: '5/8',
            points: 1,
          ),
        ],
      ),
    );
  }

  // ==========================================
  // LESSON 2
  // ==========================================
  Lesson _createLesson2() {
    final content = [
      '# Adding Fractions',
      '',
      '## Adding Fractions with the Same Denominator',
      '',
      'This is the **easiest type** of fraction addition!',
      '',
      '### The Rule:',
      '```',
      'When denominators are the SAME:',
      '→ Keep the denominator',
      '→ Add the numerators',
      '```',
      '',
      '### Formula:',
      '```',
      'a/c + b/c = (a + b)/c',
      '```',
      '',
      '### Example 1: Simple Addition',
      '```',
      '1/5 + 2/5 = (1+2)/5 = 3/5',
      '```',
      '',
      '**Think of it like this:** You have 1 piece of a 5-piece chocolate bar, then get 2 more pieces. Now you have 3/5 of the bar!',
      '',
      '### Example 2:',
      '```',
      '3/8 + 4/8 = (3+4)/8 = 7/8',
      '```',
      '',
      '### Example 3: Adding Three Fractions',
      '```',
      '2/10 + 5/10 + 1/10 = (2+5+1)/10 = 8/10 = 4/5',
      '```',
      '',
      '---',
      '',
      '## Adding Fractions with Different Denominators',
      '',
      'This requires one extra step: finding a **common denominator**.',
      '',
      '### Step-by-Step Method:',
      '',
      '**Step 1: Find the Least Common Denominator (LCD)**',
      '',
      'The LCD is the smallest number that both denominators divide into evenly.',
      '',
      '**Step 2: Convert each fraction**',
      '',
      'Multiply each fraction to make equivalent fractions with the LCD.',
      '',
      '**Step 3: Add the numerators**',
      '',
      'Keep the common denominator.',
      '',
      '**Step 4: Simplify if possible**',
      '',
      'Reduce to lowest terms.',
      '',
      '---',
      '',
      '### Example: Add 1/3 + 1/4',
      '',
      '```',
      'Step 1: Find LCD of 3 and 4',
      '→ Multiples of 3: 3, 6, 9, 12, 15...',
      '→ Multiples of 4: 4, 8, 12, 16...',
      '→ LCD = 12 ✓',
      '',
      'Step 2: Convert to equivalent fractions',
      '→ 1/3 = (1×4)/(3×4) = 4/12',
      '→ 1/4 = (1×3)/(4×3) = 3/12',
      '',
      'Step 3: Add numerators',
      '→ 4/12 + 3/12 = 7/12',
      '',
      'Step 4: Simplify',
      '→ 7/12 is already in simplest form ✓',
      '```',
      '',
      '---',
      '',
      '### Example: Add 2/3 + 3/5',
      '',
      '```',
      'LCD of 3 and 5 = 15',
      '',
      '2/3 = (2×5)/(3×5) = 10/15',
      '3/5 = (3×3)/(5×3) = 9/15',
      '',
      '10/15 + 9/15 = 19/15 = 1 4/15 (mixed number)',
      '```',
      '',
      '---',
      '',
      '## Common Mistakes to Avoid',
      '',
      '❌ **Don\'t add denominators!**',
      '```',
      '1/3 + 1/3 ≠ 2/6  ← WRONG!',
      'Correct: 1/3 + 1/3 = 2/3  ← RIGHT!',
      '```',
      '',
      '❌ **Don\'t forget to find LCD!**',
      '```',
      '1/2 + 1/3 ≠ 2/5  ← WRONG!',
      'Correct: 1/2 + 1/3 = 3/6 + 2/6 = 5/6  ← RIGHT!',
      '```',
      '',
      '✅ **Always check if you can simplify!**',
      '```',
      '2/8 + 4/8 = 6/8 = 3/4',
      '```',
      '',
      '---',
      '',
      '## Word Problems',
      '',
      '### Problem 1: School and Play',
      'Ravi spent **1/4** of his day at school and **1/3** of his day playing. What fraction of his day did he spend on both?',
      '',
      '**Solution:**',
      '```',
      '1/4 + 1/3',
      'LCD = 12',
      '1/4 = 3/12',
      '1/3 = 4/12',
      '3/12 + 4/12 = 7/12 of his day',
      '```',
      '',
      '### Problem 2: Sharing Chocolate',
      'Priya had **5/6** of a chocolate bar. Her brother gave her **1/3** more. How much does she have now?',
      '',
      '**Solution:**',
      '```',
      '5/6 + 1/3',
      'LCD = 6',
      '1/3 = 2/6',
      '5/6 + 2/6 = 7/6 = 1 1/6 chocolate bars',
      '```',
      '',
      '---',
      '',
      '## Practice Problems',
      '',
      'Try these on your own:',
      '',
      '1. 3/10 + 4/10 = ?',
      '2. 1/2 + 1/5 = ?',
      '3. 2/3 + 1/6 = ?',
      '4. 3/4 + 1/8 = ?',
      '5. 2/5 + 3/10 = ?',
      '',
      '---',
      '',
      '**Excellent!** You can now add fractions with confidence!',
      'Take the quiz to practice more.',
    ].join('\n');

    return Lesson(
      id: 'lesson_2',
      title: 'Adding Fractions',
      content: content,
      order: 2,
      quiz: Quiz(
        id: 'quiz_2',
        questions: [
          Question(
            id: 'q6',
            type: 'mcq',
            text: 'What is 2/7 + 3/7?',
            options: ['5/7', '5/14', '6/7', '1/7'],
            correctAnswer: '5/7',
            points: 1,
          ),
          Question(
            id: 'q7',
            type: 'mcq',
            text: 'What is the LCD of 1/2 and 1/3?',
            options: ['2', '3', '5', '6'],
            correctAnswer: '6',
            points: 1,
          ),
          Question(
            id: 'q8',
            type: 'mcq',
            text: 'What is 1/2 + 1/4?',
            options: ['1/4', '2/6', '3/4', '1/2'],
            correctAnswer: '3/4',
            points: 1,
          ),
          Question(
            id: 'q9',
            type: 'true_false',
            text:
                'When adding fractions with same denominator, you add both numerators and denominators.',
            options: ['True', 'False'],
            correctAnswer: 'False',
            points: 1,
          ),
          Question(
            id: 'q10',
            type: 'mcq',
            text: 'What is 3/8 + 1/8?',
            options: ['4/16', '4/8', '1/2', 'Both B and C'],
            correctAnswer: 'Both B and C',
            points: 1,
          ),
        ],
      ),
    );
  }

  // ==========================================
  // LESSON 3
  // ==========================================
  Lesson _createLesson3() {
    final content = [
      '# Fractions in Daily Life',
      '',
      '## Why Learn Fractions?',
      '',
      'Fractions are **everywhere** in our daily lives! Understanding them helps you:',
      '',
      '- 🍳 **Cook** delicious food',
      '- 💰 **Manage money** wisely',
      '- ⏰ **Plan your time** effectively',
      '- 📏 **Measure things** accurately',
      '- 🏏 **Understand sports** statistics',
      '',
      '---',
      '',
      '## 1. Fractions in Cooking',
      '',
      '### Recipe: Making Roti/Chapati',
      '',
      '**Ingredients for 4 rotis:**',
      '- 2 cups whole wheat flour',
      '- ¾ cup water',
      '- ½ teaspoon salt',
      '- 1 tablespoon oil',
      '',
      '**To make only 2 rotis (half recipe):**',
      '- 1 cup flour (2 × ½)',
      '- ⅜ cup water (¾ × ½)',
      '- ¼ teaspoon salt (½ × ½)',
      '- ½ tablespoon oil (1 × ½)',
      '',
      '**To make 8 rotis (double recipe):**',
      '- 4 cups flour',
      '- 1½ cups water',
      '- 1 teaspoon salt',
      '- 2 tablespoons oil',
      '',
      '---',
      '',
      '## 2. Fractions in Time Management',
      '',
      '### Hours and Minutes:',
      '- ¼ hour = 15 minutes',
      '- ½ hour = 30 minutes',
      '- ¾ hour = 45 minutes',
      '',
      '### Ravi\'s Daily Schedule:',
      '- ⅓ of day (8 hours) → Sleeping',
      '- ¼ of day (6 hours) → School',
      '- ⅛ of day (3 hours) → Playing',
      '- ⅙ of day (4 hours) → Studying',
      '- ⅛ of day (3 hours) → Eating & Chores',
      '',
      '**Check:** 8 + 6 + 3 + 4 + 3 = 24 hours ✓',
      '',
      '---',
      '',
      '## 3. Fractions in Shopping',
      '',
      '### At the Market:',
      '- "½ kg of onions" = 500 grams',
      '- "¼ kg of tomatoes" = 250 grams',
      '- "¾ kg of potatoes" = 750 grams',
      '',
      '### Understanding Discounts:',
      '- **50% off** = ½ price (pay half)',
      '- **25% off** = ¼ off (pay ¾ of original)',
      '- **10% off** = 1/10 off (pay 9/10)',
      '',
      '### Example: Buying a Shirt',
      'A shirt costs ₹400 with 25% discount:',
      '',
      '```',
      'Discount = ¼ of ₹400 = ₹100',
      'You pay = ₹400 - ₹100 = ₹300',
      '```',
      '',
      '---',
      '',
      '## 4. Fractions in Agriculture',
      '',
      '### Land Distribution',
      'A farmer has 10 acres of land:',
      '- ⅖ (4 acres) for wheat',
      '- ⅕ (2 acres) for rice',
      '- ⅓ (about 3.3 acres) for vegetables',
      '- Remaining for grazing',
      '',
      '**How much for grazing?**',
      '```',
      'Total used: 2/5 + 1/5 + 1/3',
      '= 6/15 + 3/15 + 5/15',
      '= 14/15',
      '',
      'Remaining: 1 - 14/15 = 1/15 of land',
      '≈ 0.67 acres for grazing',
      '```',
      '',
      '---',
      '',
      '## 5. Fractions in Sports',
      '',
      '### Cricket:',
      '- "Scored 50 runs in 60 balls" → 5/6 run rate',
      '- "Team won ¾ of their matches"',
      '- "Batsman hit boundaries on ⅕ of deliveries"',
      '',
      '### Running:',
      '- Marathon: 42 km',
      '- Half marathon: 21 km (½)',
      '- 10K run: 10 km (about ¼ of marathon)',
      '',
      '---',
      '',
      '## Real-Life Word Problems',
      '',
      '### Problem 1: Sharing Pizza',
      'Ravi ate ⅜ of a pizza, Priya ate ¼. How much is left?',
      '',
      '**Solution:**',
      '```',
      'Total eaten: ⅜ + ¼ = ⅜ + 2/8 = ⅝',
      'Remaining: 1 - ⅝ = ⅜ of the pizza',
      '```',
      '',
      '### Problem 2: School Attendance',
      'In a class of 40 students, ⅘ were present. How many were absent?',
      '',
      '**Solution:**',
      '```',
      'Present: ⅘ of 40 = 32 students',
      'Absent: 40 - 32 = 8 students',
      '```',
      '',
      '### Problem 3: Water Tank',
      'A tank is ¾ full. If ½ of the water is used, how much remains?',
      '',
      '**Solution:**',
      '```',
      'Water used: ½ of ¾ = ⅜',
      'Remaining: ¾ - ⅜ = ⅜ of tank',
      '```',
      '',
      '---',
      '',
      '## Key Life Lessons',
      '',
      '1. ✅ **Fractions help in fair sharing** (food, money, resources)',
      '2. ✅ **Recipes use fractions** - cooking is fraction math!',
      '3. ✅ **Time management** uses fractions (quarters of an hour)',
      '4. ✅ **Shopping deals** are fractions (50% off = half price)',
      '5. ✅ **Measurement** in farming, tailoring, construction all use fractions',
      '',
      '---',
      '',
      '## Your Turn!',
      '',
      'Look for fractions in your daily life:',
      '1. How do you use fractions at home?',
      '2. Ask a shopkeeper how they use fractions',
      '3. Find fractions in newspapers or on TV',
      '4. Measure ingredients while cooking',
      '',
      '---',
      '',
      '**Congratulations!** 🎉 You\'ve completed all three lessons on fractions!',
      '',
      'You now understand:',
      '- ✅ What fractions are',
      '- ✅ How to add fractions',
      '- ✅ Where fractions are used in real life',
    ].join('\n');

    return Lesson(
      id: 'lesson_3',
      title: 'Fractions in Daily Life',
      content: content,
      order: 3,
      quiz: Quiz(
        id: 'quiz_3',
        questions: [
          Question(
            id: 'q11',
            type: 'mcq',
            text:
                'If a recipe needs ½ cup of sugar and you want half recipe, how much sugar?',
            options: ['1 cup', '½ cup', '¼ cup', '¾ cup'],
            correctAnswer: '¼ cup',
            points: 1,
          ),
          Question(
            id: 'q12',
            type: 'mcq',
            text: 'Ravi completed ⅗ of his homework. What fraction remains?',
            options: ['⅖', '⅗', '⅕', '½'],
            correctAnswer: '⅖',
            points: 1,
          ),
          Question(
            id: 'q13',
            type: 'true_false',
            text: '50% discount means you pay half the original price.',
            options: ['True', 'False'],
            correctAnswer: 'True',
            points: 1,
          ),
          Question(
            id: 'q14',
            type: 'mcq',
            text:
                'A farmer used ⅖ for rice and ⅕ for wheat. What fraction is used?',
            options: ['⅗', '⅖', '⅕', '½'],
            correctAnswer: '⅗',
            points: 1,
          ),
          Question(
            id: 'q15',
            type: 'mcq',
            text: 'If you drink 6 out of 8 glasses of water, what fraction?',
            options: ['6/8', '3/4', 'Both A and B', '1/2'],
            correctAnswer: 'Both A and B',
            points: 1,
          ),
        ],
      ),
    );
  }
}
